/* Generated By:JavaCC: Do not edit this line. ExpressionsParserConstants.java */
package com.logic.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionsParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTER = 4;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int SF = 7;
  /** RegularExpression Id. */
  int SP = 8;
  /** RegularExpression Id. */
  int LPAR = 9;
  /** RegularExpression Id. */
  int RPAR = 10;
  /** RegularExpression Id. */
  int TOP = 11;
  /** RegularExpression Id. */
  int BOTTOM = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int OR = 15;
  /** RegularExpression Id. */
  int CONDITIONAL = 16;
  /** RegularExpression Id. */
  int BICONDITIONAL = 17;
  /** RegularExpression Id. */
  int UNIVERSAL = 18;
  /** RegularExpression Id. */
  int EXISTENTIAL = 19;
  /** RegularExpression Id. */
  int SLASH = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int GREEK = 22;
  /** RegularExpression Id. */
  int DOT = 23;
  /** RegularExpression Id. */
  int EQUALS = 24;
  /** RegularExpression Id. */
  int LBRA = 25;
  /** RegularExpression Id. */
  int RBRA = 26;
  /** RegularExpression Id. */
  int NUMBER = 27;
  /** RegularExpression Id. */
  int LITERAL = 28;
  /** RegularExpression Id. */
  int VARIABLE = 29;
  /** RegularExpression Id. */
  int FUNCTION = 30;
  /** RegularExpression Id. */
  int PREDICATE = 31;

  /** Lexical state. */
  int PL = 0;
  /** Lexical state. */
  int FOL = 1;
  /** Lexical state. */
  int DEFAULT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"SF\"",
    "\"SP\"",
    "\"(\"",
    "\")\"",
    "\"\\u22a4\"",
    "\"\\u22a5\"",
    "\"\\u00ac\"",
    "\"\\u2227\"",
    "\"\\u2228\"",
    "\"\\u2192\"",
    "\"\\u2194\"",
    "\"\\u2200\"",
    "\"\\u2203\"",
    "\"/\"",
    "\",\"",
    "<GREEK>",
    "\".\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "<NUMBER>",
    "<LITERAL>",
    "<VARIABLE>",
    "<FUNCTION>",
    "<PREDICATE>",
  };

}
