/* Generated By:JavaCC: Do not edit this line. ExpressionsParserConstants.java */
package com.logic.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionsParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int LPAR = 6;
  /** RegularExpression Id. */
  int RPAR = 7;
  /** RegularExpression Id. */
  int TOP = 8;
  /** RegularExpression Id. */
  int BOTTOM = 9;
  /** RegularExpression Id. */
  int NOT = 10;
  /** RegularExpression Id. */
  int AND = 11;
  /** RegularExpression Id. */
  int OR = 12;
  /** RegularExpression Id. */
  int CONDITIONAL = 13;
  /** RegularExpression Id. */
  int BICONDITIONAL = 14;
  /** RegularExpression Id. */
  int UNIVERSAL = 15;
  /** RegularExpression Id. */
  int EXISTENTIAL = 16;
  /** RegularExpression Id. */
  int SLASH = 17;
  /** RegularExpression Id. */
  int COMMA = 18;
  /** RegularExpression Id. */
  int GREEK = 19;
  /** RegularExpression Id. */
  int CHAR = 20;
  /** RegularExpression Id. */
  int U_WORD = 21;
  /** RegularExpression Id. */
  int L_WORD = 22;
  /** RegularExpression Id. */
  int ENTER = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"\\u22a4\"",
    "\"\\u22a5\"",
    "\"\\u00ac\"",
    "\"\\u2227\"",
    "\"\\u2228\"",
    "\"\\u2192\"",
    "\"\\u2194\"",
    "\"\\u2200\"",
    "\"\\u2203\"",
    "\"/\"",
    "\",\"",
    "<GREEK>",
    "<CHAR>",
    "<U_WORD>",
    "<L_WORD>",
    "\"\\n\"",
  };

}
