/* Generated By:JavaCC: Do not edit this line. ExpressionsParserConstants.java */
package com.logic.exps.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionsParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTER = 4;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int LPAR = 7;
  /** RegularExpression Id. */
  int RPAR = 8;
  /** RegularExpression Id. */
  int TOP = 9;
  /** RegularExpression Id. */
  int BOTTOM = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int OR = 13;
  /** RegularExpression Id. */
  int CONDITIONAL = 14;
  /** RegularExpression Id. */
  int BICONDITIONAL = 15;
  /** RegularExpression Id. */
  int GREEK = 16;
  /** RegularExpression Id. */
  int LITERAL = 17;
  /** RegularExpression Id. */
  int VARIABLE = 18;
  /** RegularExpression Id. */
  int FUNCTION = 19;
  /** RegularExpression Id. */
  int PREDICATE = 20;
  /** RegularExpression Id. */
  int UNIVERSAL = 21;
  /** RegularExpression Id. */
  int EXISTENTIAL = 22;
  /** RegularExpression Id. */
  int COMMA = 23;

  /** Lexical state. */
  int PL = 0;
  /** Lexical state. */
  int FOL = 1;
  /** Lexical state. */
  int DEFAULT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"\\u22a4\"",
    "\"\\u22a5\"",
    "\"\\u00ac\"",
    "\"\\u2227\"",
    "\"\\u2228\"",
    "\"\\u2192\"",
    "\"\\u2194\"",
    "<GREEK>",
    "<LITERAL>",
    "<VARIABLE>",
    "<FUNCTION>",
    "<PREDICATE>",
    "\"\\u2200\"",
    "\"\\u2203\"",
    "\",\"",
  };

}
